read_globals = {
    "AkDebugLoad",
    "EEPChangeInfoStructure",
    "EEPGetCameraPosition",
    "EEPGetCameraRotation",
    "EEPGetCloudIntensity ",
    "EEPGetFogIntensity",
    "EEPGetHailIntensity",
    "EEPGetRainIntensity",
    "EEPGetRollingstockItemName",
    "EEPGetRollingstockItemsCount",
    "EEPGetSignal",
    "EEPGetSignalTrainName",
    "EEPGetSignalTrainsCount",
    "EEPGetSnowIntensity",
    "EEPGetSwitch",
    "EEPGetTrainActive",
    "EEPGetTrainLength",
    "EEPGetTrainRoute",
    "EEPGetTrainSpeed",
    "EEPGetWindIntensity",
    "EEPGoodsGetRotation",
    "EEPIsAuxiliaryTrackReserved",
    "EEPIsControlTrackReserved",
    "EEPIsRailTrackReserved",
    "EEPIsRoadTrackReserved",
    "EEPIsTramTrackReserved",
    "EEPLoadData",
    "EEPOnTrainCoupling",
    "EEPOnTrainExitTrainyard",
    "EEPOnTrainLooseCoupling",
    "EEPPause",
    "EEPRegisterAuxiliaryTrack",
    "EEPRegisterControlTrack",
    "EEPRegisterRailTrack",
    "EEPRegisterRoadTrack",
    "EEPRegisterTramTrack",
    "EEPRollingstockGetActive",
    "EEPRollingstockGetCouplingFront",
    "EEPRollingstockGetCouplingRear",
    "EEPRollingstockGetHook",
    "EEPRollingstockGetHookGlue",
    "EEPRollingstockGetLength",
    "EEPRollingstockGetModelType",
    "EEPRollingstockGetMotor",
    "EEPRollingstockGetOrientation",
    "EEPRollingstockGetPosition",
    "EEPRollingstockGetSmoke",
    "EEPRollingstockGetTagText",
    "EEPRollingstockGetTrack",
    "EEPSaveData",
    "EEPShowInfoStructure",
    "EEPStructureGetAxis",
    "EEPStructureGetFire",
    "EEPStructureGetLight",
    "EEPStructureGetRotation",
    "EEPStructureGetSmoke",
    "EEPStructureSetAxis",
    "EEPTime",
    "EEPTimeH",
    "EEPTimeM",
    "EEPTimeS",
    "EEPVer",
    "after_each",
    "before_each",
    "clearlog",
    "describe",
    "insulate",
    "it",
    "pending",
}

allow_defined_top = true

-- See https://luacheck.readthedocs.io/en/stable/warnings.html
-- 121 - global assignment to readonly
-- 131 - global assignment
-- 212 - unused argument
files["lua/LUA/ak/core/eep"].ignore = { "212" , "131" }
files["lua/LUA/ak/demo-anlagen"].ignore = { "131" }
files["lua/LUA/ak/data/AkSlotNamesParser.lua"].ignore = { "212" }
files["lua/LUA/ak/strasse/Road.lua"].ignore = { "131" }
files["lua/LUA/ak/data/TrackCollector.lua"].ignore = { "121", "211" }

exclude_files = {
    ".vscode",
    "lua/LUA/SlotNames_BH2.lua",
    "lua/LUA/ak/anlagen/**",
    "lua/LUA/ak/io/crc32lua.lua",
    "lua/LUA/ak/io/dkjson.lua",
    "lua/LUA/ak/io/json.lua",
    "lua/Resourcen/Anlagen/Andreas_Kreuz-Demo-Ampel/Andreas_Kreuz-Demoanlage-Ampel-Grundmodelle.lua",
    "lua/Resourcen/Anlagen/Andreas_Kreuz-Demo-Testen/Andreas_Kreuz-Lua-Testbeispiel.lua",
    "lua/Resourcen/Anlagen/Andreas_Kreuz-Tutorial-Ampelkreuzung/Andreas_Kreuz-Tutorial-Ampelkreuzung.lua",
    "lua/Resourcen/Anlagen/Andreas_Kreuz-Tutorial-Ampelkreuzung/Andreas_Kreuz-Tutorial-Ampelkreuzung-2.lua",
    "lua/modell-pakete",
    "web-app",
    "web-server"
}
