describe("EepSimulator manual API", function()
    insulate("train state", function()
        require("ak.core.eep.EepSimulator")

        it("stores routes per train", function()
            assert.is_true(EEPSetTrainRoute("#RouteTrain", "RB20"))

            local ok, route = EEPGetTrainRoute("#RouteTrain")
            assert.is_true(ok)
            assert.equals("RB20", route)
        end)

        it("returns the default route for unknown trains", function()
            local ok, route = EEPGetTrainRoute("#UnknownTrain")
            assert.is_false(ok)
            assert.equals("Alle", route)
        end)

        it("keeps the route when a train is split", function()
            local EepSimulator = require("ak.core.eep.EepSimulator")

            EepSimulator.addTrain("#SplitRouteTrain", "RouteLead", "RouteTail")
            assert.is_true(EEPSetTrainRoute("#SplitRouteTrain", "RB21"))

            EepSimulator.splitTrain("#SplitRouteTrain", 1)

            local okOld, oldRoute = EEPGetTrainRoute("#SplitRouteTrain")
            local okNew, newRoute = EEPGetTrainRoute("#SplitRouteTrain;001")

            assert.is_true(okOld)
            assert.equals("RB21", oldRoute)
            assert.is_true(okNew)
            assert.equals("RB21", newRoute)
        end)

        it("stores train lights by source", function()
            assert.is_true(EEPSetTrainLight("#LightTrain", true, 2))

            local okBlinker, blinkerOn = EEPGetTrainLight("#LightTrain", 2)
            local okDefault, defaultOn = EEPGetTrainLight("#LightTrain")

            assert.is_true(okBlinker)
            assert.is_true(blinkerOn)
            assert.is_true(okDefault)
            assert.is_false(defaultOn)
        end)

        it("stores train coupling state", function()
            assert.is_true(EEPSetTrainCouplingFront("#CouplingTrain", true))
            assert.is_true(EEPSetTrainCouplingRear("#CouplingTrain", false))

            local okFront, frontState = EEPGetTrainCouplingFront("#CouplingTrain")
            local okRear, rearState = EEPGetTrainCouplingRear("#CouplingTrain")

            assert.is_true(okFront)
            assert.equals(1, frontState)
            assert.is_true(okRear)
            assert.equals(2, rearState)
        end)
    end)

    insulate("trainyard state", function()
        local EepSimulator = require("ak.core.eep.EepSimulator")

        EepSimulator.addTrainToTrainyard(3, "#DepotTrain")

        it("lists trainyard entries", function()
            assert.equals(1, EEPGetTrainyardItemsCount(3))
            assert.equals("#DepotTrain", EEPGetTrainyardItemName(3, 0))
            assert.equals(1, EEPGetTrainyardItemStatus(3, "#DepotTrain", 0))
        end)

        it("detects trains waiting in the depot", function()
            local ok, depotId = EEPIsTrainInTrainyard("#DepotTrain")
            assert.is_true(ok)
            assert.equals(3, depotId)
        end)

        it("moves trains out of the depot", function()
            assert.is_true(EEPGetTrainFromTrainyard(3, "#DepotTrain", 0))
            assert.equals(0, EEPGetTrainyardItemStatus(3, "#DepotTrain", 0))

            local ok, depotId = EEPIsTrainInTrainyard("#DepotTrain")
            assert.is_false(ok)
            assert.is_nil(depotId)
        end)

        it("moves trains back into a depot", function()
            assert.is_true(EEPPutTrainToTrainyard(4, "#DepotTrain"))
            assert.equals(1, EEPGetTrainyardItemsCount(4))
            assert.equals("#DepotTrain", EEPGetTrainyardItemName(4, 0))
            assert.equals(1, EEPGetTrainyardItemStatus(4, "#DepotTrain", 0))

            local ok, depotId = EEPIsTrainInTrainyard("#DepotTrain")
            assert.is_true(ok)
            assert.equals(4, depotId)
        end)
    end)

    insulate("camera state", function()
        require("ak.core.eep.EepSimulator")

        it("stores perspective camera per train and globally", function()
            assert.is_true(EEPSetPerspectiveCamera(9, "#CameraTrain"))

            local okTrain, trainPerspective = EEPGetPerspectiveCamera("#CameraTrain")
            local okGlobal, globalPerspective = EEPGetPerspectiveCamera()

            assert.is_true(okTrain)
            assert.equals(9, trainPerspective)
            assert.is_true(okGlobal)
            assert.equals(9, globalPerspective)
        end)

        it("stores a user camera with the documented signature", function()
            assert.is_true(EEPRollingstockSetUserCamera("Salonwagen", -4, 0, 2, 180, 90, 1))

            local ok, posX, posY, posZ, rotH, rotV = EEPRollingstockGetUserCamera("Salonwagen")
            assert.is_true(ok)
            assert.equals(-4, posX)
            assert.equals(0, posY)
            assert.equals(2, posZ)
            assert.equals(180, rotH)
            assert.equals(90, rotV)
        end)

        it("keeps compatibility with the old simulator signature", function()
            assert.is_true(EEPRollingstockSetUserCamera("LegacyCar", 1, 2, 3, 120, 45, 0, true))

            local ok, posX, posY, posZ, rotH, rotV = EEPRollingstockGetUserCamera("LegacyCar")
            assert.is_true(ok)
            assert.equals(1, posX)
            assert.equals(2, posY)
            assert.equals(3, posZ)
            assert.equals(120, rotH)
            assert.equals(45, rotV)
        end)
    end)

    insulate("rollingstock train state", function()
        local EepSimulator = require("ak.core.eep.EepSimulator")

        EepSimulator.addTrain("#RollingTrain", "Lead", "Middle", "Tail")
        EepSimulator.addTrain("#ReverseRollingTrain", "ReverseLead", "ReverseLeadTail")
        EepSimulator.setRollingStockOrientation("ReverseLead", false)
        EEPRollingstockSetCouplingRear("ReverseLead", 3)
        EepSimulator.addTrain("#ReverseTailTrain", "ReverseTailLead", "ReverseTail")
        EepSimulator.setRollingStockOrientation("ReverseTail", false)
        EepSimulator.addTrain("#SplitRollingTrain", "SplitLead", "SplitMiddle", "SplitTail")
        EepSimulator.splitTrain("#SplitRollingTrain", 1)
        EepSimulator.setRollingStockOrientation("DetachedLead", false)
        EEPRollingstockSetCouplingRear("DetachedLead", 3)

        it("derives couplings from train order for forward rolling stock", function()
            local okLeadOrientation, leadFrontForward = EEPRollingstockGetOrientation("Lead")
            local okLeadFront, leadFront = EEPRollingstockGetCouplingFront("Lead")
            local okLeadRear, leadRear = EEPRollingstockGetCouplingRear("Lead")
            local okMiddleFront, middleFront = EEPRollingstockGetCouplingFront("Middle")
            local okMiddleRear, middleRear = EEPRollingstockGetCouplingRear("Middle")
            local okTailFront, tailFront = EEPRollingstockGetCouplingFront("Tail")
            local okTailRear, tailRear = EEPRollingstockGetCouplingRear("Tail")

            assert.is_true(okLeadOrientation)
            assert.is_true(leadFrontForward)
            assert.is_true(okLeadFront)
            assert.equals(2, leadFront)
            assert.is_true(okLeadRear)
            assert.equals(3, leadRear)
            assert.is_true(okMiddleFront)
            assert.equals(3, middleFront)
            assert.is_true(okMiddleRear)
            assert.equals(3, middleRear)
            assert.is_true(okTailFront)
            assert.equals(3, tailFront)
            assert.is_true(okTailRear)
            assert.equals(2, tailRear)
        end)

        it("uses the rollingstock orientation for the first vehicle", function()
            local okOrientation, reverseLeadFrontForward = EEPRollingstockGetOrientation("ReverseLead")
            local okFront, reverseLeadFront = EEPRollingstockGetCouplingFront("ReverseLead")
            local okRear, reverseLeadRear = EEPRollingstockGetCouplingRear("ReverseLead")

            assert.is_true(okOrientation)
            assert.is_false(reverseLeadFrontForward)
            assert.is_true(okFront)
            assert.equals(3, reverseLeadFront)
            assert.is_true(okRear)
            assert.equals(3, reverseLeadRear)
        end)

        it("keeps the last forward rollingstock coupled toward the train", function()
            local okOrientation, tailFrontForward = EEPRollingstockGetOrientation("Tail")
            local okFront, tailFront = EEPRollingstockGetCouplingFront("Tail")
            local okRear, tailRear = EEPRollingstockGetCouplingRear("Tail")

            assert.is_true(okOrientation)
            assert.is_true(tailFrontForward)
            assert.is_true(okFront)
            assert.equals(3, tailFront)
            assert.is_true(okRear)
            assert.equals(2, tailRear)
        end)

        it("keeps the last reverse rollingstock coupled toward the train", function()
            local okOrientation, reverseTailFrontForward = EEPRollingstockGetOrientation("ReverseTail")
            local okFront, reverseTailFront = EEPRollingstockGetCouplingFront("ReverseTail")
            local okRear, reverseTailRear = EEPRollingstockGetCouplingRear("ReverseTail")

            assert.is_true(okOrientation)
            assert.is_false(reverseTailFrontForward)
            assert.is_true(okFront)
            assert.equals(2, reverseTailFront)
            assert.is_true(okRear)
            assert.equals(3, reverseTailRear)
        end)

        it("recomputes exposed couplings after splitting a train", function()
            local okOldRear, splitLeadRear = EEPRollingstockGetCouplingRear("SplitLead")
            local okNewFront, splitMiddleFront = EEPRollingstockGetCouplingFront("SplitMiddle")
            local okNewRear, splitMiddleRear = EEPRollingstockGetCouplingRear("SplitMiddle")

            assert.is_true(okOldRear)
            assert.equals(2, splitLeadRear)
            assert.is_true(okNewFront)
            assert.equals(2, splitMiddleFront)
            assert.is_true(okNewRear)
            assert.equals(3, splitMiddleRear)
        end)

        it("creates an implicit train for a standalone rollingstock", function()
            local okOrientation, detachedFrontForward = EEPRollingstockGetOrientation("DetachedLead")
            local okFront, detachedFront = EEPRollingstockGetCouplingFront("DetachedLead")
            local okRear, detachedRear = EEPRollingstockGetCouplingRear("DetachedLead")

            assert.equals(1, EEPGetRollingstockItemsCount("#DetachedLead"))
            assert.equals("DetachedLead", EEPGetRollingstockItemName("#DetachedLead", 0))
            assert.is_true(okOrientation)
            assert.is_false(detachedFrontForward)
            assert.is_true(okFront)
            assert.equals(2, detachedFront)
            assert.is_true(okRear)
            assert.equals(3, detachedRear)
        end)

        it("maps train front coupling to the exposed side of the first rollingstock", function()
            EepSimulator.addTrain("#TrainFrontCoupling", "FrontReverseLead", "FrontReverseTail")
            EepSimulator.setRollingStockOrientation("FrontReverseLead", false)

            assert.is_true(EEPSetTrainCouplingFront("#TrainFrontCoupling", false))

            local okTrainFront, trainFront = EEPGetTrainCouplingFront("#TrainFrontCoupling")
            local okFront, frontReverseLeadFront = EEPRollingstockGetCouplingFront("FrontReverseLead")
            local okRear, frontReverseLeadRear = EEPRollingstockGetCouplingRear("FrontReverseLead")

            assert.is_true(okTrainFront)
            assert.equals(2, trainFront)
            assert.is_true(okFront)
            assert.equals(3, frontReverseLeadFront)
            assert.is_true(okRear)
            assert.equals(2, frontReverseLeadRear)
        end)

        it("maps train rear coupling to the exposed side of the last rollingstock", function()
            EepSimulator.addTrain("#TrainRearCoupling", "RearLead", "RearReverseTail")
            EepSimulator.setRollingStockOrientation("RearReverseTail", false)

            assert.is_true(EEPSetTrainCouplingRear("#TrainRearCoupling", false))

            local okTrainRear, trainRear = EEPGetTrainCouplingRear("#TrainRearCoupling")
            local okFront, rearReverseTailFront = EEPRollingstockGetCouplingFront("RearReverseTail")
            local okRear, rearReverseTailRear = EEPRollingstockGetCouplingRear("RearReverseTail")

            assert.is_true(okTrainRear)
            assert.equals(2, trainRear)
            assert.is_true(okFront)
            assert.equals(2, rearReverseTailFront)
            assert.is_true(okRear)
            assert.equals(3, rearReverseTailRear)
        end)

        it("reflects rollingstock coupling overrides in the train coupling", function()
            EepSimulator.addTrain("#TrainRollingOverride", "OverrideLead", "OverrideTail")
            EEPRollingstockSetCouplingFront("OverrideLead", 3)
            EEPRollingstockSetCouplingRear("OverrideTail", 3)

            local okFront, trainFront = EEPGetTrainCouplingFront("#TrainRollingOverride")
            local okRear, trainRear = EEPGetTrainCouplingRear("#TrainRollingOverride")

            assert.is_true(okFront)
            assert.equals(3, trainFront)
            assert.is_true(okRear)
            assert.equals(3, trainRear)
        end)
    end)
end)
