describe("EepFunktionen.lua", function()
    insulate("EEPSave/Load", function()
        require("ce.hub.eep.EepSimulator")

        local ok1 = EEPSaveData(1, true)
        local ok2 = EEPSaveData(2, false)
        it("Could save true", function() assert.is_true(ok1) end)
        it("Could save false", function() assert.is_true(ok2) end)

        local loadOk1, val1 = EEPLoadData(1)
        local loadOk2, val2 = EEPLoadData(2)
        it("Could load 1", function() assert.is_true(loadOk1) end)
        it("Correct val 1", function() assert.is_true(val1) end)
        it("Could load 2", function() assert.is_true(loadOk2) end)
        it("Correct val 2", function() assert.is_false(val2) end)
    end)

    insulate("Trains", function()
        local EepSimulator = require("ce.hub.eep.EepSimulator")

        local countInitial = EEPGetRollingstockItemsCount("#Train1")
        it("", function() assert.equals(0, countInitial) end)

        EepSimulator.simulateAddTrain("#Train1", "RollingStock 1", "RollingStock 2")
        local countAfterInsert = EEPGetRollingstockItemsCount("#Train1")
        it("", function() assert.equals(2, countAfterInsert) end)

        EepSimulator.simulateSplitTrain("#Train1", 1)
        local countAfterSplit = EEPGetRollingstockItemsCount("#Train1")
        local countAfterSplitNewTrain = EEPGetRollingstockItemsCount("#Train1;001")
        local firstAfterSplit = EEPGetRollingstockItemName("#Train1", 0)
        local firstAfterSplitNewTrain = EEPGetRollingstockItemName("#Train1;001", 0)
        it("", function() assert.equals(1, countAfterSplit) end)
        it("", function() assert.equals(1, countAfterSplitNewTrain) end)
        it("", function() assert.equals("RollingStock 1", firstAfterSplit) end)
        it("", function() assert.equals("RollingStock 2", firstAfterSplitNewTrain) end)
    end)

    insulate("simulate train and rollingstock changes", function()
        local EepSimulator = require("ce.hub.eep.EepSimulator")

        EepSimulator.simulateAddTrain("#RenameTrain", "RenameLead", "RenameTail")
        EepSimulator.simulatePlaceTrainOnRailTrack(4, "#RenameTrain")
        EepSimulator.simulateQueueTrainOnSignal(61, "#RenameTrain")
        EepSimulator.simulateAddRollingStock("LooseWagon")
        EepSimulator.simulateAddRollingStock("LooseWagon")
        EepSimulator.simulateAddRollingStock("AppendWagon", "#RenameTrain")
        EepSimulator.simulateAddRollingStock("AppendWagon", "#RenameTrain")
        EEPSetTrainSpeed("#RenameTrain", 42)
        EepSimulator.simulateAddRollingStock("AppendWagon", "#RenameTrain")
        EepSimulator.simulateRenameTrain("#RenameTrain", "#RenamedTrain")
        EepSimulator.simulateRenameRollingStock("RenameLead", "RenamedLead")

        local railRegistered, railOccupied, occupyingTrain = EEPIsRailTrackReserved(4, true)

        it("renames trains independently", function()
            assert.equals(0, EEPGetRollingstockItemsCount("#RenameTrain"))
            assert.equals(5, EEPGetRollingstockItemsCount("#RenamedTrain"))
            assert.equals("RenamedLead", EEPGetRollingstockItemName("#RenamedTrain", 0))
            assert.equals("RenameTail", EEPGetRollingstockItemName("#RenamedTrain", 1))
            assert.equals("AppendWagon", EEPGetRollingstockItemName("#RenamedTrain", 2))
            assert.equals("AppendWagon;001", EEPGetRollingstockItemName("#RenamedTrain", 3))
            assert.equals("AppendWagon;002", EEPGetRollingstockItemName("#RenamedTrain", 4))
        end)

        it("updates train references on rename and clears signal queues after current speed changes", function()
            assert.is_true(railRegistered)
            assert.is_true(railOccupied)
            assert.equals("#RenamedTrain", occupyingTrain)
            assert.equals("DUMMY", EEPGetSignalTrainName(61, 1))
        end)

        it("renames rollingstock independently", function()
            local okRenamed, renamedFrontForward = EEPRollingstockGetOrientation("RenamedLead")
            local okOldName = select(1, EEPRollingstockGetOrientation("RenameLead"))
            assert.is_true(okRenamed)
            assert.is_true(renamedFrontForward)
            assert.is_false(okOldName)
        end)

        it("adds standalone rollingstock as implicit single train", function()
            assert.equals(1, EEPGetRollingstockItemsCount("#LooseWagon"))
            assert.equals("LooseWagon", EEPGetRollingstockItemName("#LooseWagon", 0))
        end)

        it("renames duplicate standalone rollingstock on insert", function()
            assert.equals(1, EEPGetRollingstockItemsCount("#LooseWagon;001"))
            assert.equals("LooseWagon;001", EEPGetRollingstockItemName("#LooseWagon;001", 0))
        end)

        it("renames duplicate appended rollingstock on insert", function()
            assert.equals(5, EEPGetRollingstockItemsCount("#RenamedTrain"))
            assert.equals("AppendWagon", EEPGetRollingstockItemName("#RenamedTrain", 2))
            assert.equals("AppendWagon;001", EEPGetRollingstockItemName("#RenamedTrain", 3))
            assert.equals("AppendWagon;002", EEPGetRollingstockItemName("#RenamedTrain", 4))
        end)

        it("keeps the speed of an existing train when appending rollingstock", function()
            local ok, speed = EEPGetTrainSpeed("#RenamedTrain")
            assert.is_true(ok)
            assert.equals(42, speed)
        end)

        it("keeps both speeds when renaming a train", function()
            local okCurrent, currentSpeed = EEPGetTrainSpeed("#RenamedTrain")
            local okTarget, targetSpeed = EEPGetTrainSpeed("#RenamedTrain", true)
            assert.is_true(okCurrent)
            assert.is_true(okTarget)
            assert.equals(42, currentSpeed)
            assert.equals(42, targetSpeed)
        end)
    end)

    insulate("train speed current/target behavior", function()
        local EepSimulator = require("ce.hub.eep.EepSimulator")

        EepSimulator.simulateAddTrain("#SpeedTrain", "SpeedLead")

        it("sets current and target speed by default", function()
            EEPSetTrainSpeed("#SpeedTrain", 42)
            local okCurrent, currentSpeed = EEPGetTrainSpeed("#SpeedTrain")
            local okTarget, targetSpeed = EEPGetTrainSpeed("#SpeedTrain", true)
            assert.is_true(okCurrent)
            assert.is_true(okTarget)
            assert.equals(42, currentSpeed)
            assert.equals(42, targetSpeed)
        end)

        it("accepts false and 0 as current speed selector", function()
            EEPSetTrainSpeed("#SpeedTrain", 21, false)
            local okFalse, currentSpeedFalse = EEPGetTrainSpeed("#SpeedTrain", false)
            local okZero, currentSpeedZero = EEPGetTrainSpeed("#SpeedTrain", 0)
            assert.is_true(okFalse)
            assert.is_true(okZero)
            assert.equals(21, currentSpeedFalse)
            assert.equals(21, currentSpeedZero)
        end)

        it("sets only target speed while a queued train keeps its current speed", function()
            EepSimulator.simulateQueueTrainOnSignal(71, "#SpeedTrain")
            EEPSetTrainSpeed("#SpeedTrain", 80, true)
            local okCurrent, currentSpeed = EEPGetTrainSpeed("#SpeedTrain")
            local okTarget, targetSpeed = EEPGetTrainSpeed("#SpeedTrain", true)
            assert.is_true(okCurrent)
            assert.is_true(okTarget)
            assert.equals(21, currentSpeed)
            assert.equals(80, targetSpeed)
            assert.equals("#SpeedTrain", EEPGetSignalTrainName(71, 1))
        end)

        it("accepts 1 as target speed selector", function()
            local okTarget, targetSpeed = EEPGetTrainSpeed("#SpeedTrain", 1)
            assert.is_true(okTarget)
            assert.equals(80, targetSpeed)
        end)

        it("clears signal queues when setting the current speed again", function()
            EEPSetTrainSpeed("#SpeedTrain", 50)
            local okCurrent, currentSpeed = EEPGetTrainSpeed("#SpeedTrain")
            local okTarget, targetSpeed = EEPGetTrainSpeed("#SpeedTrain", true)
            assert.is_true(okCurrent)
            assert.is_true(okTarget)
            assert.equals(50, currentSpeed)
            assert.equals(50, targetSpeed)
            assert.equals("DUMMY", EEPGetSignalTrainName(71, 1))
        end)
    end)

    insulate("EEPGetTrainFromTrainyard", function()
        local EepSimulator = require("ce.hub.eep.EepSimulator")

        EepSimulator.simulateAddTrainToTrainyard(9, "#DepotTrainByName", 0, 1)
        EepSimulator.simulateAddTrainToTrainyard(10, "#DepotTrainBySlot", 4, 1)

        it("accepts depotSlot and departureOrientation when dispatching by name", function()
            local ok = EEPGetTrainFromTrainyard(9, "#DepotTrainByName", 0, 3)
            local inDepot = select(1, EEPIsTrainInTrainyard("#DepotTrainByName"))
            assert.is_true(ok)
            assert.is_false(inDepot)
        end)

        it("accepts depotSlot and departureOrientation when dispatching by slot", function()
            local ok = EEPGetTrainFromTrainyard(10, "", 4, 1)
            local inDepot = select(1, EEPIsTrainInTrainyard("#DepotTrainBySlot"))
            assert.is_true(ok)
            assert.is_false(inDepot)
        end)
    end)
    insulate("EEPRollingstock hook state", function()
        local EepSimulator = require("ce.hub.eep.EepSimulator")

        it("stores hook and glue state on the rollingstock entry and keeps it on rename", function()
            EepSimulator.simulateAddRollingStock("HookWagon")
            EEPRollingstockSetHook("HookWagon", true)
            EEPRollingstockSetHookGlue("HookWagon", true)
            EepSimulator.simulateRenameRollingStock("HookWagon", "HookWagonRenamed")

            local okHook, hookStatus = EEPRollingstockGetHook("HookWagonRenamed")
            local okGlue, glueStatus = EEPRollingstockGetHookGlue("HookWagonRenamed")
            local _, oldHookStatus = EEPRollingstockGetHook("HookWagon")
            local _, oldGlueStatus = EEPRollingstockGetHookGlue("HookWagon")

            assert.is_true(okHook)
            assert.is_true(okGlue)
            assert.equals(1, hookStatus)
            assert.equals(1, glueStatus)
            assert.equals(0, oldHookStatus)
            assert.equals(0, oldGlueStatus)
        end)
    end)
    insulate("EEPGetPerspectiveCamera", function()
        local EepSimulator = require("ce.hub.eep.EepSimulator")

        it("stores cameraPosition on the train and returns it by train name", function()
            EepSimulator.simulateAddTrain("#CameraTrainA", "CameraLeadA")
            local okSet = EEPSetPerspectiveCamera(3, "#CameraTrainA")
            local okGet, cameraPosition = EEPGetPerspectiveCamera("#CameraTrainA")
            assert.is_true(okSet)
            assert.is_true(okGet)
            assert.equals(3, cameraPosition)
        end)

        it("keeps train cameraPosition when renaming a train", function()
            EepSimulator.simulateRenameTrain("#CameraTrainA", "#CameraTrainB")
            local okGet, cameraPosition = EEPGetPerspectiveCamera("#CameraTrainB")
            assert.is_true(okGet)
            assert.equals(3, cameraPosition)
        end)

        it("stores the global perspective camera separately", function()
            local okSet = EEPSetPerspectiveCamera(5)
            local okGet, cameraPosition = EEPGetPerspectiveCamera()
            assert.is_true(okSet)
            assert.is_true(okGet)
            assert.equals(5, cameraPosition)
        end)

        it("returns false for unknown train camera positions", function()
            local okGet = EEPGetPerspectiveCamera("#UnknownTrain")
            assert.is_false(okGet)
        end)
    end)
    insulate("EEPStructure axisPositions", function()
        require("ce.hub.eep.EepSimulator")
        local EepSimulatorStore = require("ce.hub.eep.EepSimulatorStore")

        it("stores structure axis positions on the structure only when needed", function()
            local beforeOk, beforePosition = EEPStructureGetAxis("#14", "Unbekannt")
            local structureBeforeSet = EepSimulatorStore.state.structures["#14"]
            EEPStructureSetAxis("#14", "AchseA", 30)
            local afterOk, afterPosition = EEPStructureGetAxis("#14", "AchseA")
            local missingOk, missingPosition = EEPStructureGetAxis("#14", "Unbekannt")
            local structureAfterSet = EepSimulatorStore.state.structures["#14"]
            assert.is_true(beforeOk)
            assert.equals(0, beforePosition)
            assert.is_true(structureBeforeSet == nil or structureBeforeSet.axisPositions == nil)
            assert.is_true(afterOk)
            assert.equals(30, afterPosition)
            assert.is_true(missingOk)
            assert.equals(0, missingPosition)
            assert.same({ AchseA = 30 }, structureAfterSet.axisPositions)
        end)
    end)

    insulate("EEPRollingstock userCamera", function()
        local EepSimulator = require("ce.hub.eep.EepSimulator")
        local EepSimulatorStore = require("ce.hub.eep.EepSimulatorStore")

        it("stores userCamera on the rollingstock entry and keeps it on rename", function()
            EepSimulator.simulateAddRollingStock("CameraWagon")
            EEPRollingstockSetUserCamera("CameraWagon", 1, 2, 3, 4, 5)
            EepSimulator.simulateRenameRollingStock("CameraWagon", "CameraWagonRenamed")

            local okRenamed, posX, posY, posZ, rotH, rotV = EEPRollingstockGetUserCamera("CameraWagonRenamed")
            local okOld = select(1, EEPRollingstockGetUserCamera("CameraWagon"))
            local okUnknown = select(1, EEPRollingstockGetUserCamera("UnknownWagon"))
            local renamedEntry = EepSimulatorStore.state.trains["#CameraWagon"].rollingstockEntries[1]

            assert.is_true(okRenamed)
            assert.equals(1, posX)
            assert.equals(2, posY)
            assert.equals(3, posZ)
            assert.equals(4, rotH)
            assert.equals(5, rotV)
            assert.is_false(okOld)
            assert.is_false(okUnknown)
            assert.equals("CameraWagonRenamed", renamedEntry.name)
            assert.same({
                posX = 1,
                posY = 2,
                posZ = 3,
                rotH = 4,
                rotV = 5,
                setDirectly = false
            }, renamedEntry.userCamera)
            assert.is_nil(EepSimulatorStore.state.camera.userCameraByRollingstockName)
        end)
    end)

    insulate("EEPStructureSetLight", function()
        require("ce.hub.eep.EepSimulator")
        it("", function() assert.equals("#1234", string.gsub("#1234", "(#%d*).*", "%1")) end)
        it("", function() assert.equals("#1234", string.gsub("#1234_SomeImmoModel", "(#%d*).*", "%1")) end)
        it("", function() assert.equals("#123", string.gsub("#123_", "(#%d*).*", "%1")) end)

        EEPStructureSetLight("#14", true)
        local _, on = EEPStructureGetLight("#14")
        it("on", function() assert.is_true(on) end)
        EEPStructureSetLight("#14", false)
        local _, off = EEPStructureGetLight("#14")
        it("off", function() assert.is_false(off) end)

        local _, off2 = EEPStructureGetLight("#15")
        it("off unknown", function() assert.is_false(off2) end)
    end)
    insulate("EEPVer", function()
        require("ce.hub.eep.EepSimulator")
        it("EEPVer has value \"15\"", function() assert.are.equals(16.3, EEPVer) end)
    end)

    insulate("clearlog", function()
        require("ce.hub.eep.EepSimulator")
        it("clearlog() works ", function() clearlog() end)
    end)
    describe("EEPGetSignalTrainsCount / EEPGetSignalTrainName - Simulating signals on train", function()
        insulate("single train in queue", function()
            local EEPSimulator = require("ce.hub.eep.EepSimulator")
            EEPSimulator.simulateQueueTrainOnSignal(51, "#train1-A")

            it("no one waits on signal 50", function() assert.equals(0, EEPGetSignalTrainsCount(50)) end)
            it("only train1 waits on signal 51", function()
                assert.equals(1, EEPGetSignalTrainsCount(51))
                assert.equals("#train1-A", EEPGetSignalTrainName(51, 1))
            end)
        end)

        insulate("two trains in queue", function()
            local EEPSimulator = require("ce.hub.eep.EepSimulator")
            EEPSimulator.simulateQueueTrainOnSignal(52, "#train1-B")
            EEPSimulator.simulateQueueTrainOnSignal(52, "#train2-B")

            it("train1 and train2 wait on signal 52", function()
                assert.equals(2, EEPGetSignalTrainsCount(52))
            end)
            it("train1 and train2 wait on signal 52",
               function() assert.equals("#train1-B", EEPGetSignalTrainName(52, 1)) end)
            it("train1 and train2 wait on signal 52",
               function() assert.equals("#train2-B", EEPGetSignalTrainName(52, 2)) end)
        end)

        insulate("second train moves up, if first train leaves", function()
            local EEPSimulator = require("ce.hub.eep.EepSimulator")
            EEPSimulator.simulateQueueTrainOnSignal(53, "#train1")
            EEPSimulator.simulateQueueTrainOnSignal(53, "#train2")
            EEPSimulator.simulateRemoveTrainFromSignal(53, "#train1")

            it("only train2 waits on signal 53", function()
                assert.equals(1, EEPGetSignalTrainsCount(53))
                assert.equals("#train2", EEPGetSignalTrainName(53, 1))
            end)
        end)

        insulate("all trains are removed correctly", function()
            local EEPSimulator = require("ce.hub.eep.EepSimulator")
            EEPSimulator.simulateQueueTrainOnSignal(54, "#train1")
            EEPSimulator.simulateQueueTrainOnSignal(54, "#train2")
            EEPSimulator.simulateRemoveAllTrainsFromSignal(54)

            it("no waits on signal 54", function() assert.equals(0, EEPGetSignalTrainsCount(54)) end)
        end)
    end)
end)
