insulate("Check traffic light sequence", function ()
    require("ak.core.eep.EepSimulator")
    local ModuleRegistry = require("ak.core.ModuleRegistry")
    local crossingLuaModule = require("ak.road.CrossingLuaModule")
    local schedulerLuaModule = require("ak.scheduler.SchedulerLuaModule")
    ModuleRegistry.registerModules(crossingLuaModule, schedulerLuaModule)

    local modNames = ModuleRegistry.getModuleNames()
    it("modNames size   ", function () assert.equals(3, #modNames) end)
    it("Scheduler first!", function () assert.equals("ak.scheduler.SchedulerLuaModule", modNames[1]) end)
    it("Core second!    ", function () assert.equals("ak.core.CoreLuaModule", modNames[2]) end)
    it("Crossing second!", function () assert.equals("ak.road.CrossingLuaModule", modNames[3]) end)
end)
