---@meta

---@class TransitSettings
---@field showDepartureTippText boolean
---@field saveSlot number|nil
---@field saveSettings fun():nil
---@field setShowDepartureTippText fun(value: boolean):nil

---@class Line
---@field type string
---@field trafficType string
---@field lineSegments table<string, LineSegment>
---@field id string
---@field nr string
---@field debug boolean
---@field forName fun(name: string):Line
---@field new fun(self: Line, o: table):Line
---@field addSection fun(self: Line, routeName: string, destination: string):LineSegment
---@field scheduleDeparture fun(trainName: string, station: RoadStation, timeInMinutes: number):nil
---@field trainDeparted fun(trainName: string, station: RoadStation):nil
---@field toJsonStatic fun(self: Line):table
---@field getLines fun():table<string, Line>

---@class LineSegment
---@field id string
---@field type string
---@field line Line
---@field destination string
---@field routeName string
---@field stationInfos table[]
---@field nextLineSegmentInfo table|nil
---@field debug boolean
---@field new fun(self: LineSegment, routeName: string, line: Line, destination: string):LineSegment
---@field addStop fun(self: LineSegment, platform: Platform, timeToStation?: number):nil
---@field setNextSection fun(self: LineSegment, newLineSegment: LineSegment, timeInMinutes: number):nil
---@field getAllSegments fun(self: LineSegment):LineSegment[]
---@field nextStationList fun(self: LineSegment, routeName: string, nextStation?: RoadStation, currentStation?: RoadStation):table[]
---@field getLastStation fun(self: LineSegment):RoadStation|nil
---@field getFirstStation fun(self: LineSegment):RoadStation|nil
---@field prepareDepartureAt fun(self: LineSegment, train: Train, nextStation: RoadStation, timeInMinutes: number):nil
---@field trainDeparted fun(self: LineSegment, train: Train, currentStation: RoadStation):nil
---@field toJsonStatic fun(self: LineSegment):table

---@class StationQueueEntry
---@field trainName string
---@field line string
---@field destination string
---@field timeInMinutes number
---@field platform string
---@field new fun(self: StationQueueEntry, trainName: string, destination: string, line: string, timeInMinutes: number, platform: string):StationQueueEntry
---@field keyFor fun(trainName: string, destination: string, line: string):string
---@field getKey fun(self: StationQueueEntry):string

---@class StationQueue
---@field type string
---@field entries table<string, StationQueueEntry>
---@field entriesByArrival StationQueueEntry[]
---@field new fun(self: StationQueue):StationQueue
---@field push fun(self: StationQueue, trainName: string, destination: string, line: string, timeInMinutes: number, platform?: string):nil
---@field pop fun(self: StationQueue, trainName: string, destination: string, line: string):nil
---@field getTrainEntries fun(self: StationQueue, platform?: string):table

---@class Platform
---@field type string
---@field id string
---@field roadStation RoadStation
---@field platformNumber number
---@field new fun(self: Platform, roadStation: RoadStation, platformNumber: number):Platform
---@field addDisplay fun(self: Platform, structureName: string, displayModel: table):nil

---@class RoadStation
---@field type string
---@field name string
---@field displays table
---@field platforms table<number, Platform>
---@field queue StationQueue
---@field routePlatforms table<string, table>
---@field eepSaveId number
---@field debug boolean
---@field queueToText fun(queue: StationQueue):string
---@field trainArrivesIn fun(self: RoadStation, trainName: string, destination: string, lineNr: string, timeInMinutes: number):nil
---@field trainLeft fun(self: RoadStation, trainName: string, destination: string, lineNr: string):nil
---@field setPlatform fun(self: RoadStation, segment: LineSegment, platform: number):nil
---@field updateRoutesOnPlatform fun(self: RoadStation, platformName: string):nil
---@field updateDisplays fun(self: RoadStation):nil
---@field addDisplay fun(self: RoadStation, structure: string, model: table, platformNr?: any):nil
---@field platform fun(self: RoadStation, platformNr: any):Platform
---@field new fun(self: RoadStation, name: string, eepSaveId: number):RoadStation
---@field forName fun(name: string):RoadStation
---@field showTippText fun():nil
