name: CI Tests for Web-App

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install server
        uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "npm"

      - name: Web-Server Install
        run: npm install
        working-directory: web-server

      - name: Web-App Install
        run: npm install
        working-directory: web-app-react

      - name: Web-Server Build (includes building the Web-App)
        run: npm run-script build
        working-directory: web-server

      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          start: npm run-script start-server-headless
          working-directory: web-app-react
          wait-on: "http://localhost:3000"
          config: baseUrl=http://localhost:3000
          record: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
