name: CI Tests for Web-App

on: [push, pull_request]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "yarn"

      - name: Enable Corepack
        run: corepack enable

      - name: Install via Yarn
        run: yarn install --immutable

      - name: Web-Server Build (includes building the Web-App)
        run: yarn workspace @ak/web-server run build

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          install: false
          start: yarn run start-server-headless
          working-directory: apps/web-app
          wait-on: "http://localhost:3000/server"
          record: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
